# CORE CONSTANTS, ONLY CHANGE IT IF YOU KNOW WHAT YOU ARE DOING!
WAYPOINT_DIFFERENCE_THRESHOLD = 0.01
ADDON_DATA_POSITION = ["HEALTH", "MANA", "X", "Y", "COMBAT", "TARGET HEALTH", "FACING", "TARGET DISTANCE", "LAST ABILITY", "TARGET ID"]
TURN_THRESHOLD = 0.1
RAD_PER_TURN = 0.0534

# --- BEHAVIOR ----

# OPERATORS
GREATER = "GREATER"
GREATER_EQUALS = "GREATER EQUALS"
LESS = "LESS"
LESS_EQUALS = "LESS EQUALS"
EQUALS = "EQUALS"
NOT_EQUALS = "NOT EQUALS"

# ACTIONS
VOID = 'void'
CAST = 'cast'


#LUA API COMMANDS
RELEASE_SPIRIT = '/run RepopMe()'
ACCEPT_REZ = "/run AcceptResurrection()"

