WAYPOINT_DIFFERENCE_THRESHOLD = 0.1
ADDON_DATA_POSITION = ["HEALTH", "MANA", "X", "Y", "COMBAT", "TARGET HEALTH", "TARGET DISTANCE", "FACING"]
WAYPOINT_DIFFERENCE_THRESHOLD = 0.1
TURN_THRESHOLD = 0.1
RAD_PER_TURN = 0.05
